// export const LoremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit
// sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Dolor magna eget est lorem ipsum. Id semper risus in hendrerit gravida rutrum quisque. Phasellus faucibus scelerisque eleifend donec. Diam vel quam elementum pulvinar etiam non quam lacus. Ultricies integer quis auctor elit sed vulputate. Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis. In vitae turpis massa sed elementum tempus. Mauris augue neque gravida in fermentum. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Viverra nibh cras pulvinar mattis nunc sed blandit. Pharetra pharetra massa massa ultricies mi quis. Egestas maecenas pharetra convallis posuere morbi leo. Nisi porta lorem mollis aliquam ut porttitor leo a. Vitae semper quis lectus nulla at volutpat diam ut.

// Auctor augue mauris augue neque gravida in fermentum. Id porta nibh venenatis cras sed felis eget velit aliquet. In eu mi bibendum neque egestas congue quisque egestas diam. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Tempor id eu nisl nunc mi. Malesuada nunc vel risus commodo viverra maecenas accumsan. Nec nam aliquam sem et tortor consequat. Ultricies integer quis auctor elit sed vulputate mi sit. Leo vel fringilla est ullamcorper. Pellentesque dignissim enim sit amet venenatis urna cursus. Suscipit tellus mauris a diam maecenas. Integer quis auctor elit sed vulputate mi. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Et magnis dis parturient montes nascetur ridiculus mus. Turpis cursus in hac habitasse platea dictumst quisque. Sollicitudin ac orci phasellus egestas.

// Purus sit amet volutpat consequat. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Duis ultricies lacus sed turpis. Quis hendrerit dolor magna eget est lorem. Id velit ut tortor pretium viverra suspendisse potenti. Aliquet nec ullamcorper sit amet. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Amet nulla facilisi morbi tempus iaculis. Mollis aliquam ut porttitor leo a. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper.

// Auctor augue mauris augue neque gravida in fermentum. Quam pellentesque nec nam aliquam sem. Rutrum quisque non tellus orci ac auctor augue mauris. Feugiat nibh sed pulvinar proin. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum. Fermentum leo vel orci porta non. At lectus urna duis convallis convallis. Diam volutpat commodo sed egestas. Aliquet nibh praesent tristique magna sit. Vel eros donec ac odio. Lorem ipsum dolor sit amet. Non arcu risus quis varius quam quisque id diam. Curabitur vitae nunc sed velit dignissim sodales ut. Convallis convallis tellus id interdum velit. Risus nec feugiat in fermentum posuere urna nec. Lectus magna fringilla urna porttitor. Nam aliquam sem et tortor consequat id porta. Tellus in metus vulputate eu scelerisque felis imperdiet. Ut venenatis tellus in metus vulputate. Vehicula ipsum a arcu cursus vitae congue mauris.`;

export const LoremIpsum = `abab`;
